name: thiserror
description: A library for concisely defining error types (error enums / sealed classes) and their String representation.
version: 0.3.2
repository: https://github.com/mcmah309/thiserror

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
